name: Update Function Code

on:
  push:
    branches:
      - master

jobs:
  get-filenames:
    runs-on: ubuntu-latest
    outputs:
      lambdaArray: ${{ steps.lambda_functions.outputs.lambdas }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get functions filenames
        id: lambda_functions
        run: |
          directories=$(tree lambda_functions -d -L 1 -J | jq -j -c '.[0].contents | map(.name)')
          echo ::set-output name=lambdas::${directories}

  update-code:
    needs: get-filenames
    strategy:
      matrix:
        lambda: ${{ fromJson(needs.get-filenames.outputs.lambdaArray) }}
    runs-on: ubuntu-latest
    outputs:
        sha256: ${{ steps.create-sha256.outputs.sha256 }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create SHA256 hash
        id: create-sha256
        run: |
          echo "Creating SHA256 hash for ${{ matrix.lambda }}"
          echo "sha256=${{ hashFiles('lambda_functions/${{ matrix.lambda }}') }}" >> "$GITHUB_OUTPUT"

      - name: Get cached sha256
        id: get-cached-sha256
        run: |
          if [ -f "$GITHUB_ENV" ]; then
            source "$GITHUB_ENV"
          fi
          echo "Cached sha256: $sha256"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
